enableGlobalCache: false

enableStrictSsl: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.5.2-git.20241122.hash-2f490dd.cjs

supportedArchitectures:
  {
    os: ["current", "darwin", "linux", "win32"],
    cpu: ["current", "x64", "arm64"],
  }
